package game.questParachuteGlider
{
   public class QuestParachuteGliderData
   {
      public static const ROW_HEIGHT:int = 50;
      
      public static const COLUMN_WIDTH:int = 25;
      
      internal static const _audio:Array = ["WR_cloud_swirl.mp3","WR_phatom_shock.mp3","WR_treasurechest_open.mp3","WR_wind_gust.mp3","aj_gem_new.mp3"];
      
      public var _data:Array;
      
      public function QuestParachuteGliderData()
      {
         super();
         initLevelData();
      }
      
      private function initLevelData() : void
      {
         _data = [[{
            "row":12,
            "gems":[5,31]
         },{
            "row":16,
            "gems":[9,27]
         },{
            "row":20,
            "gems":[13,23]
         },{
            "row":25,
            "gems":[5,15,21,31]
         },{
            "row":29,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":31,
            "gems":[15,21]
         },{
            "row":33,
            "gems":[5,31]
         },{
            "row":35,
            "phantomidle":[10,26]
         },{
            "row":41,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":43,
            "gems":[11,25]
         },{
            "row":45,
            "gems":[9,27]
         },{
            "row":47,
            "gems":[7,29]
         },{
            "row":49,
            "phantomhorizontal":[15]
         },{
            "row":53,
            "gems":[11,25],
            "phantomidle":[4,32]
         },{
            "row":57,
            "gems":[9,18,27]
         },{
            "row":61,
            "gems":[7,14,22,29]
         },{
            "row":64,
            "phantomverticalDown":[18]
         },{
            "row":66,
            "gems":[10,26]
         },{
            "row":69,
            "gems":[14,22]
         },{
            "row":71,
            "gems":[4,32]
         },{
            "row":73,
            "gems":[14,22]
         },{
            "row":75,
            "gems":[4,32],
            "phantomvertical":[18]
         },{
            "row":76,
            "phantomvertical":[9,27]
         },{
            "row":77,
            "gems":[14,22],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":78,
            "phantomverticalDown":[9,27]
         },{
            "row":79,
            "gems":[4,32]
         },{
            "row":81,
            "gems":[14,22],
            "phantomvertical":[18]
         },{
            "row":83,
            "gems":[4,32]
         },{
            "row":87,
            "phantomverticalDown":[18]
         },{
            "row":88,
            "gems":[10,26]
         },{
            "row":93,
            "gems":[14,22],
            "phantomidle":[3,33]
         },{
            "row":96,
            "phantomidle":[7,29]
         },{
            "row":97,
            "gems":[18]
         },{
            "row":99,
            "phantomidle":[11,25]
         },{
            "row":103,
            "gems":[17,19]
         },{
            "row":106,
            "gems":[15,21]
         },{
            "row":107,
            "gems":[9,27]
         },{
            "row":109,
            "gems":[5,11,25,31]
         },{
            "row":113,
            "phantomhorizontal":[1,10,19,28]
         },{
            "row":116,
            "gems":[11,21,31]
         },{
            "row":119,
            "phantomhorizontalLeft":[8,17,26,35]
         },{
            "row":122,
            "gems":[5,15,25]
         },{
            "row":125,
            "phantomhorizontal":[1,10,19,28]
         },{
            "row":128,
            "gems":[11,21,31]
         },{
            "row":131,
            "phantomhorizontalLeft":[8,17,26,35]
         },{
            "row":134,
            "gems":[5,15,25]
         },{
            "row":137,
            "phantomhorizontal":[1,10,19,28]
         },{
            "row":141,
            "gems":[13,23]
         },{
            "row":143,
            "gems":[9,27]
         },{
            "row":145,
            "phantomidle":[18],
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":149,
            "gems":[9,27]
         },{
            "row":151,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":154,
            "gems":[15,21],
            "phantomidle":[5,31]
         },{
            "row":156,
            "gems":[13,23]
         },{
            "row":159,
            "phantomhorizontal":[15]
         },{
            "row":160,
            "gems":[7,29]
         },{
            "row":162,
            "gems":[15,21]
         },{
            "row":165,
            "phantomidle":[6,30]
         },{
            "row":167,
            "gems":[15,21]
         },{
            "row":169,
            "gems":[11,25]
         },{
            "row":170,
            "phantomhorizontalLeft":[21]
         },{
            "row":175,
            "gems":[7,29]
         },{
            "row":180,
            "gems":[13,23],
            "phantomidle":[5,31]
         },{
            "row":183,
            "gems":[9,27]
         },{
            "row":185,
            "gems":[5,31]
         },{
            "row":186,
            "phantomhorizontalLeft":[21]
         },{
            "row":188,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":190,
            "phantomhorizontal":[15]
         },{
            "row":193,
            "gems":[13,23]
         },{"ground":200}],[{
            "row":9,
            "gems":[18]
         },{
            "row":11,
            "gems":[7,29]
         },{
            "row":14,
            "gems":[13,23]
         },{
            "row":16,
            "gems":[9,27],
            "phantomverticalDown":[18]
         },{
            "row":18,
            "gems":[7,29]
         },{
            "row":22,
            "gems":[4,32]
         },{
            "row":24,
            "gems":[17,19],
            "phantomidle":[10,26]
         },{
            "row":26,
            "gems":[4,15,21,32]
         },{
            "row":30,
            "gems":[4,13,23,32]
         },{
            "row":32,
            "phantomidle":[18]
         },{
            "row":36,
            "gems":[9,18,27]
         },{
            "row":40,
            "gems":[9,27],
            "phantomhorizontal":[11],
            "phantomhorizontalLeft":[25]
         },{
            "row":42,
            "phantomvertical":[4,32]
         },{
            "row":44,
            "gems":[9,18,27]
         },{
            "row":48,
            "phantomhorizontal":[15]
         },{
            "row":49,
            "gems":[7,11,25,29]
         },{
            "row":51,
            "gems":[5,13,23,31]
         },{
            "row":53,
            "gems":[7,11,25,29]
         },{
            "row":54,
            "phantomhorizontalLeft":[21]
         },{
            "row":57,
            "phantomhorizontal":[24],
            "phantomhorizontalLeft":[12]
         },{
            "row":58,
            "gems":[17,19]
         },{
            "row":61,
            "gems":[5,31],
            "phantomidle":[10,26]
         },{
            "row":63,
            "gems":[3,15,21,33]
         },{
            "row":65,
            "gems":[5,31]
         },{
            "row":67,
            "gems":[9,15,21,27]
         },{
            "row":69,
            "gems":[3,17,19,33],
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":71,
            "gems":[9,15,21,27]
         },{
            "row":73,
            "gems":[5,31]
         },{
            "row":75,
            "gems":[3,15,21,33]
         },{
            "row":77,
            "gems":[5,31],
            "phantomidle":[10,26]
         },{
            "row":80,
            "gems":[17,19]
         },{
            "row":82,
            "phantomidle":[5,31]
         },{
            "row":83,
            "gems":[15,21]
         },{
            "row":85,
            "phantomidle":[9,27]
         },{
            "row":86,
            "gems":[17,19]
         },{
            "row":91,
            "phantomhorizontal":[19,28],
            "phantomhorizontalLeft":[8,17]
         },{
            "row":94,
            "gems":[5,15,21,31]
         },{
            "row":97,
            "phantomhorizontal":[1,10],
            "phantomhorizontalLeft":[26,35]
         },{
            "row":100,
            "gems":[7,11,25,29],
            "phantomidle":[18]
         },{
            "row":102,
            "gems":[9,27]
         },{
            "row":105,
            "phantomhorizontal":[19,28],
            "phantomhorizontalLeft":[8,17]
         },{
            "row":109,
            "phantomidle":[5,31]
         },{
            "row":110,
            "gems":[11,25],
            "phantomverticalDown":[18]
         },{
            "row":114,
            "gems":[9,13,23,27]
         },{
            "row":116,
            "gems":[3,33]
         },{
            "row":118,
            "gems":[7,15,21,29]
         },{
            "row":120,
            "phantomvertical":[18]
         },{
            "row":122,
            "phantomvertical":[6,30]
         },{
            "row":124,
            "gems":[13,23]
         },{
            "row":126,
            "phantomhorizontal":[9],
            "phantomhorizontalLeft":[27]
         },{
            "row":128,
            "gems":[13,23]
         },{
            "row":130,
            "phantomidle":[18]
         },{
            "row":134,
            "gems":[7,13,23,29]
         },{
            "row":136,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":138,
            "gems":[3,33]
         },{
            "row":139,
            "phantomhorizontal":[9],
            "phantomhorizontalLeft":[27]
         },{
            "row":140,
            "gems":[15,21]
         },{
            "row":142,
            "gems":[13,23],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":145,
            "gems":[7,29],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":147,
            "gems":[7,29]
         },{
            "row":150,
            "phantomidle":[5,31]
         },{
            "row":151,
            "gems":[11,25]
         },{
            "row":152,
            "phantomvertical":[18]
         },{
            "row":153,
            "gems":[13,23]
         },{
            "row":156,
            "phantomidle":[18]
         },{
            "row":157,
            "gems":[9,27],
            "phantomidle":[3,33]
         },{
            "row":160,
            "phantomverticalDown":[18]
         },{
            "row":161,
            "gems":[13,23]
         },{
            "row":164,
            "phantomidle":[7,29]
         },{
            "row":166,
            "gems":[15,21]
         },{
            "row":169,
            "phantomverticalDown":[13,25]
         },{
            "row":170,
            "gems":[7,29]
         },{
            "row":174,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":178,
            "gems":[7,29]
         },{
            "row":182,
            "gems":[11,25],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":183,
            "phantomidle":[18]
         },{
            "row":188,
            "gems":[9,27]
         },{
            "row":190,
            "phantomidle":[13,23]
         },{
            "row":193,
            "gems":[7,29]
         },{"ground":200}],[{
            "row":15,
            "gems":[15,21]
         },{
            "row":18,
            "gems":[13,23],
            "phantomverticalDown":[18]
         },{
            "row":21,
            "gems":[3,11,25,33]
         },{
            "row":24,
            "gems":[5,9,27,31]
         },{
            "row":25,
            "phantomidle":[14,22]
         },{
            "row":27,
            "gems":[7,29]
         },{
            "row":29,
            "gems":[13,23]
         },{
            "row":31,
            "gems":[5,15,21,31]
         },{
            "row":33,
            "gems":[7,29],
            "phantomvertical":[18]
         },{
            "row":35,
            "gems":[13,23]
         },{
            "row":38,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":39,
            "gems":[9,27]
         },{
            "row":42,
            "gems":[5,13,23,31]
         },{
            "row":43,
            "phantomverticalDown":[18]
         },{
            "row":45,
            "gems":[3,15,21,33],
            "phantomidle":[9,27]
         },{
            "row":48,
            "gems":[5,13,23,31]
         },{
            "row":51,
            "gems":[9,27]
         },{
            "row":55,
            "phantomidle":[18]
         },{
            "row":56,
            "phantomidle":[5,31]
         },{
            "row":58,
            "gems":[10,26]
         },{
            "row":60,
            "gems":[15,21],
            "phantomverticalDown":[18]
         },{
            "row":64,
            "gems":[6,15,21,30]
         },{
            "row":68,
            "gems":[13,23]
         },{
            "row":69,
            "gems":[3,33]
         },{
            "row":73,
            "gems":[7,29],
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":76,
            "gems":[3,33]
         },{
            "row":78,
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":80,
            "gems":[14,22],
            "phantomidle":[18]
         },{
            "row":82,
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":84,
            "gems":[3,33]
         },{
            "row":87,
            "gems":[7,29],
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":90,
            "gems":[17,19]
         },{
            "row":92,
            "gems":[15,21]
         },{
            "row":95,
            "gems":[9,27],
            "phantomverticalDown":[18]
         },{
            "row":97,
            "gems":[11,25]
         },{
            "row":100,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":103,
            "gems":[8,28],
            "phantomidle":[18]
         },{
            "row":106,
            "phantomidle":[3,33],
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":109,
            "gems":[8,28],
            "phantomidle":[18]
         },{
            "row":112,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":115,
            "gems":[8,28],
            "phantomidle":[18]
         },{
            "row":118,
            "phantomidle":[3,33],
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":121,
            "gems":[8,28]
         },{
            "row":123,
            "phantomidle":[13,23]
         },{
            "row":125,
            "gems":[7,29]
         },{
            "row":129,
            "gems":[3,15,21,33],
            "phantomverticalDown":[18]
         },{
            "row":132,
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":133,
            "gems":[11,25]
         },{
            "row":135,
            "gems":[3,33]
         },{
            "row":137,
            "phantomidle":[18],
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":139,
            "gems":[11,25]
         },{
            "row":140,
            "phantomverticalDown":[18]
         },{
            "row":141,
            "gems":[5,31]
         },{
            "row":143,
            "gems":[13,23]
         },{
            "row":147,
            "gems":[7,15,21,29]
         },{
            "row":150,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":151,
            "gems":[17,19]
         },{
            "row":153,
            "gems":[9,27]
         },{
            "row":156,
            "phantomverticalDown":[9,27]
         },{
            "row":157,
            "gems":[5,31]
         },{
            "row":160,
            "gems":[7,29],
            "phantomidle":[18]
         },{
            "row":163,
            "gems":[9,27]
         },{
            "row":165,
            "gems":[18]
         },{
            "row":166,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":169,
            "gems":[9,27]
         },{
            "row":171,
            "gems":[3,18,33]
         },{
            "row":175,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":176,
            "gems":[11,25]
         },{
            "row":179,
            "gems":[13,23]
         },{
            "row":182,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":184,
            "gems":[9,27]
         },{
            "row":187,
            "phantomvertical":[18]
         },{
            "row":188,
            "gems":[11,25]
         },{
            "row":190,
            "gems":[15,21]
         },{
            "row":191,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":193,
            "gems":[13,23]
         },{"ground":200}],[{
            "row":12,
            "gems":[15,21]
         },{
            "row":16,
            "gems":[14,22]
         },{
            "row":19,
            "gems":[7,18,29]
         },{
            "row":21,
            "gems":[5,31]
         },{
            "row":23,
            "gems":[9,27]
         },{
            "row":25,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":27,
            "phantomidle":[5,31]
         },{
            "row":29,
            "gems":[15,21]
         },{
            "row":31,
            "gems":[5,9,27,31]
         },{
            "row":32,
            "gems":[17,19]
         },{
            "row":35,
            "gems":[7,29]
         },{
            "row":38,
            "phantomvertical":[18],
            "phantomhorizontal":[31],
            "phantomhorizontalLeft":[5]
         },{
            "row":39,
            "gems":[13,23]
         },{
            "row":42,
            "phantomverticalDown":[18]
         },{
            "row":43,
            "gems":[7,11,25,29]
         },{
            "row":45,
            "gems":[5,13,23,31]
         },{
            "row":47,
            "gems":[15,21]
         },{
            "row":49,
            "gems":[3,33],
            "phantomidle":[9,27]
         },{
            "row":53,
            "gems":[15,21]
         },{
            "row":55,
            "gems":[7,9,27,29]
         },{
            "row":59,
            "gems":[5,11,25,31]
         },{
            "row":61,
            "gems":[18]
         },{
            "row":62,
            "phantomidle":[8,28]
         },{
            "row":65,
            "gems":[8,28]
         },{
            "row":66,
            "gems":[3,33]
         },{
            "row":68,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":69,
            "gems":[18]
         },{
            "row":71,
            "gems":[8,28]
         },{
            "row":74,
            "phantomhorizontal":[1,10],
            "phantomhorizontalLeft":[26,35]
         },{
            "row":77,
            "gems":[3,8,28,33]
         },{
            "row":80,
            "phantomhorizontal":[1,21],
            "phantomhorizontalLeft":[15,35]
         },{
            "row":82,
            "gems":[18]
         },{
            "row":83,
            "gems":[8,28]
         },{
            "row":85,
            "phantomverticalDown":[13,23]
         },{
            "row":89,
            "gems":[8,28]
         },{
            "row":90,
            "phantomvertical":[3,33]
         },{
            "row":92,
            "phantomidle":[13,23]
         },{
            "row":94,
            "gems":[3,33]
         },{
            "row":96,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":98,
            "gems":[18]
         },{
            "row":100,
            "gems":[14,22]
         },{
            "row":102,
            "gems":[11,25],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":103,
            "phantomidle":[18]
         },{
            "row":106,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":108,
            "gems":[5,15,21,31]
         },{
            "row":114,
            "gems":[9,15,21,27]
         },{
            "row":115,
            "phantomidle":[4,32]
         },{
            "row":118,
            "gems":[7,29],
            "phantomvertical":[11,25]
         },{
            "row":120,
            "gems":[13,23],
            "phantomverticalDown":[9,27]
         },{
            "row":122,
            "gems":[5,31]
         },{
            "row":124,
            "phantomhorizontalLeft":[21]
         },{
            "row":126,
            "gems":[3,11,25,33]
         },{
            "row":129,
            "phantomhorizontal":[15]
         },{
            "row":130,
            "phantomvertical":[7,29]
         },{
            "row":132,
            "gems":[2,9,27,34]
         },{
            "row":134,
            "phantomhorizontalLeft":[21]
         },{
            "row":136,
            "phantomidle":[7,29]
         },{
            "row":138,
            "gems":[15,21]
         },{
            "row":139,
            "gems":[3,33],
            "phantomidle":[11,25]
         },{
            "row":141,
            "gems":[15,21]
         },{
            "row":143,
            "gems":[7,29]
         },{
            "row":147,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":149,
            "phantomhorizontal":[33],
            "phantomhorizontalLeft":[3]
         },{
            "row":153,
            "gems":[9,17,19,27]
         },{
            "row":157,
            "gems":[13,23],
            "phantomhorizontal":[15]
         },{
            "row":159,
            "gems":[7,29]
         },{
            "row":162,
            "phantomhorizontal":[15],
            "phantomverticalDown":[9,27]
         },{
            "row":163,
            "gems":[3,33]
         },{
            "row":167,
            "gems":[7,29]
         },{
            "row":170,
            "phantomidle":[14,22]
         },{
            "row":171,
            "gems":[7,29]
         },{
            "row":173,
            "gems":[9,27]
         },{
            "row":176,
            "phantomhorizontal":[27],
            "phantomhorizontalLeft":[9]
         },{
            "row":177,
            "gems":[15,21]
         },{
            "row":179,
            "gems":[5,31]
         },{
            "row":182,
            "gems":[9,27],
            "phantomhorizontal":[15]
         },{
            "row":186,
            "gems":[13,23]
         },{
            "row":187,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":190,
            "gems":[13,23]
         },{
            "row":193,
            "gems":[9,27],
            "phantomidle":[18]
         },{"ground":200}],[{
            "row":12,
            "gems":[15,21]
         },{
            "row":16,
            "gems":[13,23]
         },{
            "row":17,
            "gems":[3,33]
         },{
            "row":19,
            "gems":[18]
         },{
            "row":21,
            "gems":[7,29]
         },{
            "row":23,
            "gems":[15,21]
         },{
            "row":25,
            "phantomidle":[4,18,32]
         },{
            "row":27,
            "gems":[7,29]
         },{
            "row":29,
            "gems":[13,23]
         },{
            "row":31,
            "gems":[5,31]
         },{
            "row":35,
            "gems":[3,11,25,33]
         },{
            "row":36,
            "phantomidle":[18]
         },{
            "row":39,
            "gems":[1,35],
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":41,
            "gems":[9,27]
         },{
            "row":44,
            "phantomidle":[18]
         },{
            "row":45,
            "gems":[13,23],
            "phantomidle":[5,31]
         },{
            "row":47,
            "gems":[1,35]
         },{
            "row":48,
            "phantomidle":[9,27]
         },{
            "row":51,
            "gems":[7,15,21,29]
         },{
            "row":53,
            "gems":[9,13,23,27],
            "phantomvertical":[18]
         },{
            "row":55,
            "gems":[11,25]
         },{
            "row":56,
            "phantomvertical":[4,32]
         },{
            "row":57,
            "gems":[18]
         },{
            "row":59,
            "gems":[13,23]
         },{
            "row":61,
            "gems":[9,15,21,27]
         },{
            "row":63,
            "gems":[18]
         },{
            "row":65,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":67,
            "gems":[9,27],
            "phantomverticalDown":[18]
         },{
            "row":71,
            "gems":[5,31]
         },{
            "row":73,
            "gems":[18],
            "phantomhorizontal":[1,10],
            "phantomhorizontalLeft":[26,35]
         },{
            "row":75,
            "gems":[3,33],
            "phantomverticalDown":[18]
         },{
            "row":77,
            "gems":[5,31]
         },{
            "row":79,
            "gems":[11,25]
         },{
            "row":81,
            "gems":[5,13,23,31]
         },{
            "row":83,
            "gems":[15,21]
         },{
            "row":84,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":87,
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":89,
            "gems":[15,21]
         },{
            "row":91,
            "gems":[9,27]
         },{
            "row":92,
            "phantomidle":[18]
         },{
            "row":93,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":96,
            "gems":[13,23]
         },{
            "row":99,
            "gems":[3,33],
            "phantomidle":[8,28]
         },{
            "row":100,
            "gems":[13,23]
         },{
            "row":103,
            "gems":[5,31]
         },{
            "row":104,
            "gems":[15,21]
         },{
            "row":107,
            "gems":[7,29],
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":111,
            "gems":[11,25]
         },{
            "row":113,
            "gems":[3,33]
         },{
            "row":115,
            "gems":[8,28]
         },{
            "row":117,
            "gems":[16,20],
            "phantomverticalDown":[12,24]
         },{
            "row":120,
            "gems":[8,28],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":123,
            "gems":[18]
         },{
            "row":124,
            "phantomhorizontal":[10],
            "phantomhorizontalLeft":[26]
         },{
            "row":128,
            "gems":[7,11,25,29],
            "phantomidle":[18]
         },{
            "row":132,
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":133,
            "gems":[18]
         },{
            "row":136,
            "phantomhorizontal":[10],
            "phantomhorizontalLeft":[26]
         },{
            "row":139,
            "phantomverticalDown":[3,33]
         },{
            "row":140,
            "phantomvertical":[18]
         },{
            "row":141,
            "gems":[7,29]
         },{
            "row":144,
            "gems":[9,27]
         },{
            "row":147,
            "gems":[11,25]
         },{
            "row":148,
            "phantomvertical":[18]
         },{
            "row":149,
            "phantomidle":[7,29]
         },{
            "row":152,
            "gems":[5,9,27,31]
         },{
            "row":154,
            "gems":[7,29]
         },{
            "row":156,
            "gems":[13,23]
         },{
            "row":157,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":158,
            "phantomidle":[18]
         },{
            "row":161,
            "gems":[15,21]
         },{
            "row":163,
            "gems":[3,11,25,33]
         },{
            "row":168,
            "gems":[7,29]
         },{
            "row":171,
            "gems":[15,21],
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":178,
            "gems":[11,25]
         },{
            "row":179,
            "phantomvertical":[5,31]
         },{
            "row":183,
            "gems":[5,31]
         },{
            "row":184,
            "gems":[13,23]
         },{
            "row":187,
            "gems":[11,25]
         },{
            "row":189,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":191,
            "gems":[11,25],
            "phantomidle":[5,31]
         },{
            "row":193,
            "gems":[13,23]
         },{"ground":200}],[{
            "row":13,
            "gems":[11,25]
         },{
            "row":16,
            "gems":[13,23]
         },{
            "row":17,
            "phantomidle":[5,31]
         },{
            "row":19,
            "gems":[18]
         },{
            "row":21,
            "gems":[7,29]
         },{
            "row":24,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":27,
            "gems":[7,29]
         },{
            "row":30,
            "gems":[3,11,25,33]
         },{
            "row":32,
            "phantomidle":[18]
         },{
            "row":33,
            "gems":[7,29]
         },{
            "row":36,
            "gems":[11,25]
         },{
            "row":37,
            "phantomidle":[3,33]
         },{
            "row":39,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":41,
            "gems":[7,29]
         },{
            "row":44,
            "phantomidle":[18]
         },{
            "row":45,
            "gems":[7,29]
         },{
            "row":47,
            "gems":[1,13,23,35]
         },{
            "row":50,
            "phantomidle":[7,29]
         },{
            "row":51,
            "gems":[1,13,23,35]
         },{
            "row":53,
            "phantomvertical":[18]
         },{
            "row":55,
            "gems":[3,11,25,33]
         },{
            "row":57,
            "gems":[7,29]
         },{
            "row":60,
            "gems":[18]
         },{
            "row":61,
            "gems":[7,29]
         },{
            "row":62,
            "gems":[15,21]
         },{
            "row":64,
            "gems":[3,33]
         },{
            "row":65,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":67,
            "gems":[9,27],
            "phantomverticalDown":[18]
         },{
            "row":69,
            "gems":[11,25],
            "phantomvertical":[3,33]
         },{
            "row":71,
            "gems":[15,21]
         },{
            "row":73,
            "gems":[18],
            "phantomhorizontal":[1,10],
            "phantomhorizontalLeft":[26,35]
         },{
            "row":77,
            "gems":[5,31]
         },{
            "row":78,
            "phantomidle":[18]
         },{
            "row":79,
            "gems":[11,25]
         },{
            "row":81,
            "gems":[5,13,23,31]
         },{
            "row":83,
            "gems":[15,21]
         },{
            "row":84,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":87,
            "phantomidle":[7,29]
         },{
            "row":88,
            "gems":[15,21]
         },{
            "row":92,
            "gems":[15,21]
         },{
            "row":93,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":94,
            "gems":[7,29]
         },{
            "row":96,
            "phantomidle":[12,24]
         },{
            "row":98,
            "gems":[7,29]
         },{
            "row":102,
            "gems":[7,29]
         },{
            "row":104,
            "gems":[15,21]
         },{
            "row":105,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":108,
            "gems":[15,21]
         },{
            "row":109,
            "phantomidle":[3,33]
         },{
            "row":112,
            "gems":[11,25]
         },{
            "row":113,
            "gems":[3,33]
         },{
            "row":116,
            "gems":[7,29]
         },{
            "row":117,
            "phantomverticalDown":[12,24]
         },{
            "row":118,
            "gems":[16,20]
         },{
            "row":120,
            "gems":[7,29],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":123,
            "gems":[18]
         },{
            "row":124,
            "gems":[7,29],
            "phantomidle":[12,24]
         },{
            "row":128,
            "gems":[7,29],
            "phantomidle":[18]
         },{
            "row":131,
            "phantomhorizontal":[2,12],
            "phantomhorizontalLeft":[24,34]
         },{
            "row":134,
            "gems":[7,18,29]
         },{
            "row":137,
            "phantomidle":[12,24]
         },{
            "row":139,
            "phantomverticalDown":[3,33]
         },{
            "row":141,
            "gems":[7,29],
            "phantomvertical":[18]
         },{
            "row":144,
            "gems":[11,25]
         },{
            "row":147,
            "gems":[15,21]
         },{
            "row":148,
            "phantomvertical":[18]
         },{
            "row":149,
            "phantomidle":[7,29]
         },{
            "row":152,
            "gems":[3,33],
            "phantomhorizontal":[15]
         },{
            "row":154,
            "gems":[7,29]
         },{
            "row":155,
            "gems":[13,18,23]
         },{
            "row":157,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":158,
            "phantomhorizontalLeft":[21]
         },{
            "row":160,
            "gems":[7,29]
         },{
            "row":163,
            "gems":[3,33],
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":165,
            "gems":[18]
         },{
            "row":168,
            "gems":[7,29]
         },{
            "row":170,
            "phantomidle":[3,33],
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":172,
            "gems":[7,29]
         },{
            "row":174,
            "phantomverticalDown":[18]
         },{
            "row":176,
            "gems":[11,25]
         },{
            "row":179,
            "phantomhorizontal":[31],
            "phantomhorizontalLeft":[5]
         },{
            "row":180,
            "gems":[15,21]
         },{
            "row":183,
            "gems":[11,25]
         },{
            "row":185,
            "phantomhorizontal":[15]
         },{
            "row":186,
            "gems":[7,29]
         },{
            "row":189,
            "phantomhorizontalLeft":[21]
         },{
            "row":190,
            "phantomidle":[4,32]
         },{
            "row":191,
            "gems":[11,25]
         },{
            "row":193,
            "gems":[7,29]
         },{"ground":200}],[{
            "row":13,
            "gems":[9,27]
         },{
            "row":16,
            "gems":[5,13,23,31]
         },{
            "row":18,
            "phantomidle":[18]
         },{
            "row":22,
            "phantomvertical":[9,27]
         },{
            "row":23,
            "gems":[5,13,23,31]
         },{
            "row":26,
            "gems":[9,27]
         },{
            "row":30,
            "gems":[18],
            "phantomidle":[4,32]
         },{
            "row":31,
            "gems":[13,23]
         },{
            "row":32,
            "phantomidle":[18]
         },{
            "row":33,
            "gems":[9,27]
         },{
            "row":35,
            "phantomidle":[5,31]
         },{
            "row":36,
            "gems":[13,23]
         },{
            "row":39,
            "gems":[18],
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":41,
            "gems":[11,25]
         },{
            "row":44,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":47,
            "gems":[1,35]
         },{
            "row":49,
            "phantomidle":[18],
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":51,
            "gems":[1,35]
         },{
            "row":54,
            "phantomhorizontal":[15]
         },{
            "row":55,
            "gems":[3,11,25,33]
         },{
            "row":57,
            "gems":[7,18,29]
         },{
            "row":60,
            "gems":[13,23],
            "phantomhorizontalLeft":[21]
         },{
            "row":63,
            "gems":[7,29]
         },{
            "row":64,
            "gems":[3,33]
         },{
            "row":65,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":67,
            "phantomverticalDown":[18]
         },{
            "row":68,
            "gems":[7,29]
         },{
            "row":70,
            "phantomidle":[3,33]
         },{
            "row":73,
            "gems":[11,25],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":75,
            "gems":[13,23]
         },{
            "row":76,
            "gems":[5,31]
         },{
            "row":77,
            "phantomvertical":[18]
         },{
            "row":79,
            "phantomhorizontal":[27],
            "phantomhorizontalLeft":[9]
         },{
            "row":82,
            "gems":[5,31]
         },{
            "row":83,
            "gems":[11,25]
         },{
            "row":84,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":85,
            "gems":[15,21]
         },{
            "row":87,
            "gems":[1,35],
            "phantomidle":[7,29]
         },{
            "row":89,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":93,
            "gems":[1,15,21,35],
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":96,
            "phantomidle":[12,24]
         },{
            "row":98,
            "gems":[7,29]
         },{
            "row":101,
            "gems":[9,27]
         },{
            "row":102,
            "phantomvertical":[4,32]
         },{
            "row":104,
            "gems":[15,21]
         },{
            "row":105,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":108,
            "gems":[15,21]
         },{
            "row":109,
            "phantomidle":[3,33]
         },{
            "row":112,
            "gems":[18]
         },{
            "row":113,
            "gems":[3,33]
         },{
            "row":116,
            "gems":[7,29]
         },{
            "row":117,
            "phantomvertical":[12,24]
         },{
            "row":118,
            "gems":[3,11,25,33]
         },{
            "row":120,
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":121,
            "gems":[13,23]
         },{
            "row":123,
            "gems":[18]
         },{
            "row":124,
            "phantomidle":[7,29]
         },{
            "row":127,
            "phantomidle":[18]
         },{
            "row":128,
            "gems":[7,29]
         },{
            "row":131,
            "phantomhorizontal":[2,12,22,32]
         },{
            "row":134,
            "gems":[7,17,27]
         },{
            "row":137,
            "phantomhorizontalLeft":[4,14,24,34]
         },{
            "row":140,
            "gems":[9,19,29]
         },{
            "row":144,
            "gems":[3,13,23,33],
            "phantomidle":[9,27]
         },{
            "row":148,
            "gems":[3,18,33],
            "phantomidle":[13,23]
         },{
            "row":151,
            "phantomverticalDown":[18]
         },{
            "row":152,
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":154,
            "gems":[7,29]
         },{
            "row":155,
            "gems":[13,23]
         },{
            "row":157,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":158,
            "phantomhorizontalLeft":[21]
         },{
            "row":160,
            "gems":[7,29]
         },{
            "row":163,
            "gems":[3,33],
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":165,
            "gems":[18]
         },{
            "row":167,
            "gems":[15,21]
         },{
            "row":168,
            "phantomidle":[7,29]
         },{
            "row":170,
            "phantomverticalDown":[18]
         },{
            "row":171,
            "gems":[3,33]
         },{
            "row":172,
            "gems":[11,25]
         },{
            "row":174,
            "gems":[1,35]
         },{
            "row":175,
            "phantomverticalDown":[18]
         },{
            "row":176,
            "phantomvertical":[7,29]
         },{
            "row":177,
            "gems":[13,23]
         },{
            "row":179,
            "phantomhorizontal":[31],
            "phantomhorizontalLeft":[5]
         },{
            "row":180,
            "phantomverticalDown":[18]
         },{
            "row":182,
            "gems":[13,23]
         },{
            "row":184,
            "gems":[9,27]
         },{
            "row":185,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":187,
            "gems":[5,31]
         },{
            "row":189,
            "gems":[11,25]
         },{
            "row":191,
            "phantomvertical":[11,25]
         },{
            "row":193,
            "gems":[1,15,21,35]
         },{"ground":200}],[{
            "row":13,
            "gems":[11,25]
         },{
            "row":16,
            "gems":[13,23]
         },{
            "row":18,
            "gems":[5,31]
         },{
            "row":19,
            "phantomidle":[18]
         },{
            "row":20,
            "phantomidle":[10,26]
         },{
            "row":23,
            "gems":[3,13,23,33]
         },{
            "row":25,
            "phantomidle":[18]
         },{
            "row":26,
            "gems":[8,28]
         },{
            "row":27,
            "gems":[3,13,23,33]
         },{
            "row":30,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":31,
            "gems":[13,23]
         },{
            "row":33,
            "phantomidle":[18]
         },{
            "row":35,
            "gems":[13,23],
            "phantomhorizontal":[26],
            "phantomhorizontalLeft":[10]
         },{
            "row":37,
            "gems":[18]
         },{
            "row":40,
            "gems":[13,23],
            "phantomidle":[18],
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":43,
            "gems":[8,18,28]
         },{
            "row":46,
            "gems":[3,14,22,33]
         },{
            "row":49,
            "gems":[10,26],
            "phantomidle":[18],
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":52,
            "gems":[3,14,22,33]
         },{
            "row":55,
            "gems":[8,18,28]
         },{
            "row":58,
            "gems":[13,23],
            "phantomidle":[5,18,31]
         },{
            "row":61,
            "gems":[18]
         },{
            "row":63,
            "gems":[7,29]
         },{
            "row":64,
            "gems":[3,33],
            "phantomverticalDown":[18]
         },{
            "row":66,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":68,
            "gems":[7,29]
         },{
            "row":71,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":73,
            "gems":[11,25]
         },{
            "row":75,
            "gems":[5,13,23,31],
            "phantomvertical":[18]
         },{
            "row":78,
            "gems":[9,27]
         },{
            "row":80,
            "phantomidle":[18],
            "phantomhorizontal":[30],
            "phantomhorizontalLeft":[6]
         },{
            "row":82,
            "gems":[5,13,23,31]
         },{
            "row":84,
            "gems":[18]
         },{
            "row":86,
            "phantomidle":[7,29]
         },{
            "row":87,
            "gems":[14,22]
         },{
            "row":89,
            "phantomidle":[18]
         },{
            "row":90,
            "gems":[10,26],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":93,
            "gems":[6,18,30]
         },{
            "row":96,
            "gems":[2,18,34],
            "phantomidle":[11,25]
         },{
            "row":99,
            "gems":[18]
         },{
            "row":100,
            "gems":[8,28]
         },{
            "row":102,
            "phantomvertical":[4,32]
         },{
            "row":104,
            "gems":[15,21]
         },{
            "row":105,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":108,
            "gems":[8,28]
         },{
            "row":109,
            "phantomidle":[3,33]
         },{
            "row":111,
            "phantomvertical":[18]
         },{
            "row":113,
            "gems":[2,14,22,34]
         },{
            "row":115,
            "gems":[8,28]
         },{
            "row":117,
            "gems":[2,34],
            "phantomidle":[12,24]
         },{
            "row":120,
            "gems":[8,18,28],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":123,
            "gems":[14,22]
         },{
            "row":124,
            "phantomidle":[5,31]
         },{
            "row":126,
            "gems":[10,26],
            "phantomidle":[18]
         },{
            "row":129,
            "gems":[14,22]
         },{
            "row":131,
            "phantomhorizontal":[2,12],
            "phantomhorizontalLeft":[24,34]
         },{
            "row":132,
            "gems":[18]
         },{
            "row":136,
            "gems":[12,24],
            "phantomidle":[7,18,29]
         },{
            "row":140,
            "gems":[6,18,30]
         },{
            "row":141,
            "phantomidle":[11,25]
         },{
            "row":144,
            "gems":[13,23],
            "phantomidle":[18],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":148,
            "gems":[6,18,30]
         },{
            "row":152,
            "gems":[3,33],
            "phantomidle":[18],
            "phantomvertical":[11,25]
         },{
            "row":154,
            "gems":[7,29]
         },{
            "row":156,
            "gems":[3,18,33]
         },{
            "row":157,
            "phantomidle":[11,25]
         },{
            "row":160,
            "gems":[7,15,21,29]
         },{
            "row":164,
            "gems":[11,25],
            "phantomidle":[18],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":168,
            "gems":[7,18,29],
            "phantomidle":[3,33]
         },{
            "row":172,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":174,
            "phantomidle":[6,30]
         },{
            "row":176,
            "gems":[15,21]
         },{
            "row":177,
            "gems":[1,35]
         },{
            "row":180,
            "gems":[18],
            "phantomidle":[13,23]
         },{
            "row":181,
            "gems":[8,28]
         },{
            "row":185,
            "gems":[3,13,23,33],
            "phantomidle":[8,28]
         },{
            "row":189,
            "gems":[8,28],
            "phantomidle":[18]
         },{
            "row":193,
            "gems":[1,15,21,35],
            "phantomidle":[8,28]
         },{"ground":200}],[{
            "row":13,
            "gems":[3,33]
         },{
            "row":16,
            "phantomidle":[11,25]
         },{
            "row":17,
            "gems":[3,33]
         },{
            "row":19,
            "phantomidle":[18]
         },{
            "row":21,
            "gems":[3,33]
         },{
            "row":23,
            "gems":[13,23]
         },{
            "row":25,
            "gems":[3,33],
            "phantomidle":[18]
         },{
            "row":27,
            "gems":[13,23]
         },{
            "row":29,
            "phantomidle":[18]
         },{
            "row":30,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":31,
            "gems":[13,23]
         },{
            "row":33,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":35,
            "phantomhorizontal":[26],
            "phantomhorizontalLeft":[10]
         },{
            "row":37,
            "gems":[5,18,31]
         },{
            "row":40,
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":41,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":46,
            "gems":[3,9,27,33],
            "phantomidle":[18]
         },{
            "row":49,
            "gems":[14,22],
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":52,
            "gems":[3,9,27,33]
         },{
            "row":54,
            "phantomidle":[18]
         },{
            "row":56,
            "gems":[9,27]
         },{
            "row":58,
            "phantomidle":[5,31]
         },{
            "row":59,
            "gems":[18]
         },{
            "row":60,
            "gems":[9,27]
         },{
            "row":63,
            "gems":[18]
         },{
            "row":64,
            "gems":[3,33]
         },{
            "row":66,
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":67,
            "gems":[18]
         },{
            "row":68,
            "gems":[7,29]
         },{
            "row":70,
            "phantomidle":[18]
         },{
            "row":71,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":73,
            "gems":[18]
         },{
            "row":74,
            "gems":[7,29]
         },{
            "row":75,
            "gems":[13,23]
         },{
            "row":77,
            "gems":[18]
         },{
            "row":78,
            "gems":[7,29]
         },{
            "row":80,
            "phantomhorizontal":[32],
            "phantomhorizontalLeft":[4]
         },{
            "row":81,
            "gems":[18]
         },{
            "row":82,
            "gems":[7,29]
         },{
            "row":84,
            "phantomidle":[18]
         },{
            "row":86,
            "phantomidle":[7,29]
         },{
            "row":87,
            "gems":[13,23]
         },{
            "row":89,
            "gems":[3,33],
            "phantomidle":[18],
            "phantomverticalDown":[8,28]
         },{
            "row":91,
            "gems":[13,23]
         },{
            "row":93,
            "gems":[3,33],
            "phantomverticalDown":[18]
         },{
            "row":95,
            "gems":[13,23]
         },{
            "row":97,
            "gems":[3,33]
         },{
            "row":98,
            "gems":[18],
            "phantomidle":[13,23]
         },{
            "row":100,
            "gems":[8,28]
         },{
            "row":101,
            "phantomidle":[3,33]
         },{
            "row":102,
            "phantomhorizontal":[15]
         },{
            "row":104,
            "gems":[8,28]
         },{
            "row":106,
            "phantomidle":[3,33],
            "phantomhorizontalLeft":[21]
         },{
            "row":108,
            "gems":[8,28]
         },{
            "row":111,
            "phantomidle":[18]
         },{
            "row":112,
            "gems":[8,28]
         },{
            "row":114,
            "gems":[18]
         },{
            "row":116,
            "gems":[2,34],
            "phantomidle":[8,28]
         },{
            "row":118,
            "gems":[18]
         },{
            "row":120,
            "gems":[8,28],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":122,
            "gems":[18]
         },{
            "row":124,
            "gems":[2,8,28,34],
            "phantomidle":[5,31]
         },{
            "row":126,
            "gems":[26],
            "phantomidle":[18]
         },{
            "row":127,
            "gems":[13,23]
         },{
            "row":128,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":131,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":133,
            "phantomidle":[7,29]
         },{
            "row":136,
            "gems":[12,24]
         },{
            "row":138,
            "gems":[3,33],
            "phantomidle":[18]
         },{
            "row":140,
            "gems":[12,24]
         },{
            "row":142,
            "phantomhorizontal":[15]
         },{
            "row":144,
            "gems":[10,26],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":146,
            "phantomhorizontalLeft":[21]
         },{
            "row":148,
            "gems":[5,31]
         },{
            "row":149,
            "gems":[18]
         },{
            "row":152,
            "gems":[5,31],
            "phantomvertical":[11,25]
         },{
            "row":153,
            "gems":[18]
         },{
            "row":154,
            "phantomverticalDown":[11,25]
         },{
            "row":156,
            "gems":[5,31]
         },{
            "row":157,
            "gems":[18]
         },{
            "row":160,
            "gems":[5,31]
         },{
            "row":161,
            "gems":[18]
         },{
            "row":164,
            "gems":[11,25],
            "phantomidle":[5,31]
         },{
            "row":165,
            "phantomidle":[18]
         },{
            "row":168,
            "gems":[8,28],
            "phantomidle":[3,33]
         },{
            "row":170,
            "phantomhorizontal":[15]
         },{
            "row":172,
            "gems":[8,28]
         },{
            "row":174,
            "gems":[18]
         },{
            "row":175,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":177,
            "gems":[3,33]
         },{
            "row":178,
            "gems":[18]
         },{
            "row":180,
            "phantomidle":[13,23]
         },{
            "row":181,
            "gems":[3,8,28,33]
         },{
            "row":182,
            "gems":[18]
         },{
            "row":185,
            "gems":[3,33],
            "phantomidle":[8,28]
         },{
            "row":186,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":189,
            "gems":[8,28]
         },{
            "row":190,
            "gems":[18],
            "phantomverticalDown":[13,23]
         },{
            "row":191,
            "phantomidle":[3,33]
         },{
            "row":193,
            "gems":[8,28]
         },{"ground":200}],[{
            "row":13,
            "gems":[11,25]
         },{
            "row":16,
            "phantomidle":[7,29]
         },{
            "row":17,
            "gems":[11,25]
         },{
            "row":19,
            "phantomidle":[18]
         },{
            "row":21,
            "gems":[11,25]
         },{
            "row":23,
            "gems":[5,31]
         },{
            "row":25,
            "phantomidle":[11,25]
         },{
            "row":27,
            "gems":[5,31]
         },{
            "row":30,
            "phantomhorizontal":[9],
            "phantomhorizontalLeft":[27]
         },{
            "row":31,
            "gems":[5,31]
         },{
            "row":32,
            "phantomidle":[18]
         },{
            "row":33,
            "gems":[13,23]
         },{
            "row":35,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":37,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":41,
            "gems":[13,23]
         },{
            "row":42,
            "phantomidle":[18]
         },{
            "row":46,
            "gems":[9,27]
         },{
            "row":49,
            "gems":[4,18,32],
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":52,
            "gems":[9,27]
         },{
            "row":54,
            "phantomidle":[18]
         },{
            "row":56,
            "gems":[9,27],
            "phantomhorizontal":[2],
            "phantomhorizontalLeft":[34]
         },{
            "row":58,
            "phantomidle":[18]
         },{
            "row":60,
            "gems":[9,27]
         },{
            "row":64,
            "gems":[3,15,21,33],
            "phantomidle":[9,27]
         },{
            "row":68,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":71,
            "phantomhorizontal":[20,29],
            "phantomhorizontalLeft":[7,16]
         },{
            "row":73,
            "gems":[18]
         },{
            "row":74,
            "gems":[11,25]
         },{
            "row":75,
            "gems":[5,31]
         },{
            "row":77,
            "phantomidle":[18]
         },{
            "row":78,
            "gems":[11,25]
         },{
            "row":80,
            "phantomidle":[5,31]
         },{
            "row":81,
            "gems":[18]
         },{
            "row":82,
            "gems":[11,25]
         },{
            "row":86,
            "phantomidle":[11,25]
         },{
            "row":87,
            "gems":[4,32]
         },{
            "row":89,
            "gems":[14,22],
            "phantomidle":[18],
            "phantomverticalDown":[9,27]
         },{
            "row":91,
            "gems":[4,32]
         },{
            "row":93,
            "gems":[14,22],
            "phantomverticalDown":[18]
         },{
            "row":95,
            "gems":[4,32]
         },{
            "row":97,
            "gems":[14,22]
         },{
            "row":100,
            "gems":[10,26],
            "phantomverticalDown":[4,32]
         },{
            "row":101,
            "phantomidle":[15,21]
         },{
            "row":104,
            "gems":[10,26]
         },{
            "row":106,
            "gems":[4,32],
            "phantomidle":[15,21]
         },{
            "row":108,
            "gems":[10,26]
         },{
            "row":112,
            "gems":[18]
         },{
            "row":113,
            "phantomvertical":[6,30]
         },{
            "row":116,
            "gems":[10,26]
         },{
            "row":118,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":120,
            "gems":[2,10,26,34]
         },{
            "row":122,
            "phantomidle":[18]
         },{
            "row":124,
            "gems":[4,32],
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":126,
            "phantomidle":[18]
         },{
            "row":127,
            "gems":[5,31]
         },{
            "row":130,
            "phantomidle":[18]
         },{
            "row":131,
            "gems":[5,31],
            "phantomvertical":[11,25]
         },{
            "row":133,
            "phantomhorizontal":[11],
            "phantomhorizontalLeft":[25]
         },{
            "row":134,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":136,
            "gems":[6,30]
         },{
            "row":138,
            "gems":[15,21],
            "phantomidle":[18]
         },{
            "row":140,
            "gems":[6,30]
         },{
            "row":144,
            "gems":[8,28],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":147,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":148,
            "gems":[13,23]
         },{
            "row":149,
            "gems":[18]
         },{
            "row":152,
            "gems":[13,23]
         },{
            "row":153,
            "gems":[8,28]
         },{
            "row":157,
            "gems":[18],
            "phantomhorizontal":[21,30],
            "phantomhorizontalLeft":[6,15]
         },{
            "row":160,
            "gems":[13,23]
         },{
            "row":161,
            "gems":[18]
         },{
            "row":164,
            "gems":[7,29],
            "phantomidle":[13,23]
         },{
            "row":168,
            "gems":[10,26],
            "phantomidle":[4,32]
         },{
            "row":169,
            "phantomidle":[18]
         },{
            "row":172,
            "gems":[10,26]
         },{
            "row":174,
            "gems":[18]
         },{
            "row":175,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":177,
            "gems":[15,21]
         },{
            "row":180,
            "gems":[18],
            "phantomidle":[5,31]
         },{
            "row":181,
            "gems":[10,26]
         },{
            "row":185,
            "gems":[15,21],
            "phantomidle":[10,26]
         },{
            "row":186,
            "gems":[5,31],
            "phantomvertical":[18]
         },{
            "row":189,
            "gems":[9,18,27]
         },{
            "row":190,
            "phantomverticalDown":[5,31]
         },{
            "row":191,
            "phantomidle":[14,22]
         },{
            "row":193,
            "gems":[10,26]
         },{"ground":200}],[{
            "row":13,
            "gems":[7,29]
         },{
            "row":16,
            "gems":[5,31],
            "phantomidle":[11,25]
         },{
            "row":19,
            "gems":[18]
         },{
            "row":21,
            "gems":[11,25]
         },{
            "row":24,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":27,
            "gems":[11,25]
         },{
            "row":30,
            "gems":[7,15,21,29]
         },{
            "row":32,
            "phantomidle":[18]
         },{
            "row":33,
            "gems":[11,25]
         },{
            "row":36,
            "gems":[7,29]
         },{
            "row":37,
            "phantomidle":[15,21]
         },{
            "row":39,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":41,
            "gems":[11,25]
         },{
            "row":43,
            "phantomidle":[18]
         },{
            "row":45,
            "gems":[11,25]
         },{
            "row":47,
            "gems":[5,18,31]
         },{
            "row":50,
            "phantomidle":[11,25]
         },{
            "row":51,
            "gems":[5,18,31]
         },{
            "row":53,
            "phantomverticalDown":[18]
         },{
            "row":55,
            "gems":[7,15,21,29]
         },{
            "row":57,
            "gems":[11,25]
         },{
            "row":60,
            "gems":[18]
         },{
            "row":61,
            "gems":[11,25]
         },{
            "row":62,
            "gems":[3,33]
         },{
            "row":64,
            "gems":[15,21]
         },{
            "row":65,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":66,
            "phantomverticalDown":[18]
         },{
            "row":67,
            "gems":[9,27]
         },{
            "row":69,
            "gems":[7,29]
         },{
            "row":71,
            "gems":[3,33],
            "phantomvertical":[15,21]
         },{
            "row":73,
            "gems":[18],
            "phantomhorizontal":[19,28],
            "phantomhorizontalLeft":[8,17]
         },{
            "row":77,
            "gems":[13,23]
         },{
            "row":78,
            "phantomidle":[18]
         },{
            "row":79,
            "gems":[7,29]
         },{
            "row":81,
            "gems":[5,13,23,31]
         },{
            "row":83,
            "gems":[3,33]
         },{
            "row":84,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":87,
            "phantomidle":[9,27]
         },{
            "row":88,
            "gems":[3,33]
         },{
            "row":92,
            "gems":[3,33]
         },{
            "row":93,
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":94,
            "gems":[11,25]
         },{
            "row":96,
            "phantomidle":[6,30]
         },{
            "row":97,
            "phantomverticalDown":[18]
         },{
            "row":98,
            "gems":[11,25]
         },{
            "row":102,
            "gems":[11,25]
         },{
            "row":104,
            "gems":[3,33]
         },{
            "row":105,
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":106,
            "phantomvertical":[18]
         },{
            "row":108,
            "gems":[3,33]
         },{
            "row":109,
            "phantomidle":[15,21]
         },{
            "row":112,
            "gems":[7,29]
         },{
            "row":113,
            "gems":[15,21]
         },{
            "row":115,
            "phantomverticalDown":[18]
         },{
            "row":116,
            "gems":[11,25]
         },{
            "row":117,
            "phantomverticalDown":[6,30]
         },{
            "row":118,
            "gems":[2,34]
         },{
            "row":120,
            "gems":[11,25]
         },{
            "row":123,
            "gems":[18]
         },{
            "row":124,
            "gems":[11,25],
            "phantomidle":[6,30]
         },{
            "row":128,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":131,
            "phantomhorizontal":[20,30],
            "phantomhorizontalLeft":[6,16]
         },{
            "row":134,
            "gems":[11,18,25]
         },{
            "row":137,
            "phantomidle":[6,30]
         },{
            "row":139,
            "phantomverticalDown":[15,21]
         },{
            "row":141,
            "gems":[11,25],
            "phantomvertical":[18]
         },{
            "row":144,
            "gems":[7,29]
         },{
            "row":147,
            "gems":[3,33]
         },{
            "row":148,
            "phantomvertical":[18]
         },{
            "row":149,
            "phantomidle":[11,25]
         },{
            "row":152,
            "gems":[15,21]
         },{
            "row":154,
            "gems":[11,25]
         },{
            "row":155,
            "gems":[5,18,31]
         },{
            "row":157,
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":160,
            "gems":[11,25]
         },{
            "row":163,
            "gems":[15,21],
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":165,
            "gems":[18]
         },{
            "row":168,
            "gems":[11,25]
         },{
            "row":170,
            "phantomidle":[15,21],
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":172,
            "gems":[11,25]
         },{
            "row":174,
            "phantomverticalDown":[18]
         },{
            "row":176,
            "gems":[7,29]
         },{
            "row":179,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":180,
            "gems":[3,33]
         },{
            "row":183,
            "gems":[7,29]
         },{
            "row":186,
            "gems":[11,25]
         },{
            "row":187,
            "phantomidle":[5,31]
         },{
            "row":190,
            "phantomidle":[14,22]
         },{
            "row":191,
            "gems":[7,29]
         },{
            "row":193,
            "gems":[11,25]
         },{"ground":200}],[{
            "row":13,
            "gems":[9,27]
         },{
            "row":16,
            "gems":[13,23]
         },{
            "row":18,
            "phantomidle":[18]
         },{
            "row":19,
            "gems":[9,27]
         },{
            "row":22,
            "gems":[5,31],
            "phantomvertical":[9,27]
         },{
            "row":23,
            "gems":[13,23]
         },{
            "row":26,
            "gems":[9,27]
         },{
            "row":29,
            "phantomidle":[13,23]
         },{
            "row":30,
            "gems":[18]
         },{
            "row":31,
            "gems":[5,31]
         },{
            "row":33,
            "gems":[9,27]
         },{
            "row":35,
            "phantomidle":[13,23]
         },{
            "row":36,
            "gems":[5,31]
         },{
            "row":39,
            "gems":[18],
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":41,
            "gems":[7,29]
         },{
            "row":43,
            "phantomidle":[18]
         },{
            "row":44,
            "gems":[13,23]
         },{
            "row":47,
            "gems":[15,21]
         },{
            "row":49,
            "phantomidle":[18],
            "phantomhorizontal":[24],
            "phantomhorizontalLeft":[12]
         },{
            "row":51,
            "gems":[15,21]
         },{
            "row":55,
            "gems":[7,15,21,29]
         },{
            "row":57,
            "gems":[11,18,25]
         },{
            "row":60,
            "gems":[5,31]
         },{
            "row":63,
            "gems":[11,25]
         },{
            "row":64,
            "gems":[15,21]
         },{
            "row":65,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":67,
            "phantomvertical":[18]
         },{
            "row":68,
            "gems":[11,25]
         },{
            "row":69,
            "phantomidle":[4,32]
         },{
            "row":73,
            "gems":[7,29],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":75,
            "gems":[5,31]
         },{
            "row":76,
            "gems":[13,23]
         },{
            "row":77,
            "phantomvertical":[18]
         },{
            "row":79,
            "phantomhorizontal":[9],
            "phantomhorizontalLeft":[27]
         },{
            "row":82,
            "gems":[13,23]
         },{
            "row":83,
            "gems":[7,29]
         },{
            "row":84,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":85,
            "gems":[3,33]
         },{
            "row":87,
            "gems":[15,21],
            "phantomidle":[11,25]
         },{
            "row":89,
            "gems":[5,31],
            "phantomidle":[18]
         },{
            "row":93,
            "gems":[3,33],
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":94,
            "gems":[15,21]
         },{
            "row":96,
            "phantomidle":[6,30]
         },{
            "row":98,
            "gems":[11,25]
         },{
            "row":101,
            "gems":[9,27]
         },{
            "row":102,
            "phantomvertical":[14,22]
         },{
            "row":104,
            "gems":[3,33]
         },{
            "row":105,
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":108,
            "gems":[3,33]
         },{
            "row":109,
            "phantomidle":[13,23]
         },{
            "row":111,
            "gems":[18]
         },{
            "row":113,
            "gems":[15,21]
         },{
            "row":116,
            "gems":[11,25]
         },{
            "row":117,
            "phantomvertical":[6,30]
         },{
            "row":118,
            "gems":[7,15,21,29]
         },{
            "row":120,
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":121,
            "gems":[5,31]
         },{
            "row":123,
            "gems":[18]
         },{
            "row":124,
            "phantomidle":[11,25]
         },{
            "row":127,
            "phantomidle":[18]
         },{
            "row":128,
            "gems":[11,25]
         },{
            "row":131,
            "phantomhorizontal":[4,14,20,30]
         },{
            "row":134,
            "gems":[9,25]
         },{
            "row":137,
            "phantomhorizontalLeft":[6,16,22,32]
         },{
            "row":140,
            "gems":[11,27]
         },{
            "row":144,
            "gems":[5,15,21,31],
            "phantomidle":[9,27]
         },{
            "row":148,
            "gems":[18],
            "phantomidle":[5,31]
         },{
            "row":151,
            "phantomverticalDown":[18]
         },{
            "row":152,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":154,
            "gems":[11,25]
         },{
            "row":155,
            "gems":[5,31]
         },{
            "row":157,
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":160,
            "gems":[11,25]
         },{
            "row":163,
            "gems":[15,21],
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":165,
            "gems":[18]
         },{
            "row":167,
            "gems":[3,33]
         },{
            "row":168,
            "phantomidle":[11,25]
         },{
            "row":171,
            "gems":[15,21],
            "phantomverticalDown":[18]
         },{
            "row":172,
            "gems":[7,29]
         },{
            "row":176,
            "phantomvertical":[11,25]
         },{
            "row":177,
            "gems":[5,31]
         },{
            "row":179,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":180,
            "phantomverticalDown":[18]
         },{
            "row":182,
            "gems":[5,31]
         },{
            "row":184,
            "gems":[9,27]
         },{
            "row":186,
            "phantomhorizontal":[4],
            "phantomhorizontalLeft":[32]
         },{
            "row":187,
            "gems":[13,23]
         },{
            "row":189,
            "gems":[7,29]
         },{
            "row":191,
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":193,
            "gems":[3,15,21,33]
         },{"ground":200}],[{
            "row":13,
            "gems":[7,29]
         },{
            "row":16,
            "gems":[5,31]
         },{
            "row":18,
            "gems":[13,23]
         },{
            "row":19,
            "phantomidle":[18]
         },{
            "row":20,
            "phantomidle":[8,28]
         },{
            "row":22,
            "gems":[14,22]
         },{
            "row":23,
            "gems":[5,31]
         },{
            "row":25,
            "phantomidle":[18]
         },{
            "row":26,
            "gems":[10,26]
         },{
            "row":27,
            "gems":[3,33]
         },{
            "row":28,
            "gems":[14,22]
         },{
            "row":30,
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":31,
            "gems":[5,31]
         },{
            "row":33,
            "phantomidle":[18]
         },{
            "row":35,
            "gems":[5,31],
            "phantomhorizontal":[8],
            "phantomhorizontalLeft":[28]
         },{
            "row":37,
            "gems":[18]
         },{
            "row":40,
            "gems":[5,31],
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":43,
            "gems":[10,18,26]
         },{
            "row":46,
            "gems":[4,15,21,32]
         },{
            "row":49,
            "gems":[8,28],
            "phantomhorizontal":[20],
            "phantomhorizontalLeft":[16]
         },{
            "row":52,
            "gems":[4,15,21,32]
         },{
            "row":55,
            "gems":[10,18,26]
         },{
            "row":58,
            "gems":[5,31]
         },{
            "row":59,
            "phantomidle":[11,25]
         },{
            "row":61,
            "gems":[18]
         },{
            "row":63,
            "gems":[11,25]
         },{
            "row":64,
            "gems":[15,21],
            "phantomverticalDown":[18]
         },{
            "row":66,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":68,
            "gems":[11,25]
         },{
            "row":71,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":73,
            "gems":[7,29]
         },{
            "row":75,
            "gems":[5,13,23,31],
            "phantomvertical":[18]
         },{
            "row":78,
            "gems":[9,27]
         },{
            "row":80,
            "phantomidle":[18],
            "phantomhorizontal":[24],
            "phantomhorizontalLeft":[12]
         },{
            "row":82,
            "gems":[5,13,23,31]
         },{
            "row":84,
            "gems":[18]
         },{
            "row":85,
            "phantomidle":[9,27]
         },{
            "row":87,
            "gems":[4,32]
         },{
            "row":88,
            "phantomidle":[18]
         },{
            "row":90,
            "gems":[8,28],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":93,
            "gems":[12,18,24]
         },{
            "row":96,
            "gems":[15,21],
            "phantomidle":[7,29]
         },{
            "row":99,
            "gems":[18]
         },{
            "row":100,
            "gems":[10,26]
         },{
            "row":102,
            "phantomvertical":[14,22]
         },{
            "row":104,
            "gems":[3,33]
         },{
            "row":105,
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":108,
            "gems":[10,26]
         },{
            "row":109,
            "phantomidle":[15,21]
         },{
            "row":111,
            "phantomvertical":[18]
         },{
            "row":113,
            "gems":[4,16,20,32]
         },{
            "row":115,
            "gems":[10,26]
         },{
            "row":117,
            "gems":[16,20],
            "phantomidle":[6,30]
         },{
            "row":120,
            "gems":[10,18,26],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":123,
            "gems":[4,32]
         },{
            "row":124,
            "phantomidle":[13,23]
         },{
            "row":126,
            "gems":[8,28],
            "phantomidle":[18]
         },{
            "row":129,
            "gems":[4,32]
         },{
            "row":131,
            "phantomhorizontal":[6],
            "phantomhorizontalLeft":[30]
         },{
            "row":132,
            "gems":[18]
         },{
            "row":136,
            "gems":[6,30],
            "phantomidle":[11,25]
         },{
            "row":140,
            "gems":[12,18,24]
         },{
            "row":141,
            "phantomidle":[7,29]
         },{
            "row":144,
            "gems":[5,31],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":148,
            "gems":[12,18,24]
         },{
            "row":152,
            "gems":[15,21],
            "phantomidle":[18],
            "phantomvertical":[7,29]
         },{
            "row":154,
            "gems":[11,25]
         },{
            "row":156,
            "gems":[15,21]
         },{
            "row":157,
            "phantomidle":[7,29]
         },{
            "row":160,
            "gems":[3,11,25,33]
         },{
            "row":164,
            "gems":[7,29],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":168,
            "gems":[6,18,30],
            "phantomidle":[11,25]
         },{
            "row":172,
            "gems":[7,29],
            "phantomidle":[18]
         },{
            "row":174,
            "phantomidle":[12,24]
         },{
            "row":176,
            "gems":[3,33]
         },{
            "row":177,
            "gems":[15,21]
         },{
            "row":180,
            "gems":[18],
            "phantomidle":[5,31]
         },{
            "row":181,
            "gems":[10,26]
         },{
            "row":185,
            "gems":[5,15,21,31],
            "phantomidle":[10,26]
         },{
            "row":189,
            "gems":[10,26],
            "phantomidle":[18]
         },{
            "row":192,
            "gems":[15,21]
         },{
            "row":193,
            "gems":[3,33],
            "phantomidle":[10,26]
         },{"ground":200}],[{
            "row":9,
            "gems":[18]
         },{
            "row":11,
            "gems":[11,25]
         },{
            "row":14,
            "gems":[5,31]
         },{
            "row":16,
            "gems":[9,27],
            "phantomverticalDown":[18]
         },{
            "row":18,
            "gems":[11,25]
         },{
            "row":22,
            "gems":[14,22]
         },{
            "row":24,
            "gems":[1,35],
            "phantomidle":[8,28]
         },{
            "row":26,
            "gems":[3,14,22,33]
         },{
            "row":30,
            "gems":[5,14,22,31]
         },{
            "row":32,
            "phantomidle":[18]
         },{
            "row":36,
            "gems":[9,18,27]
         },{
            "row":40,
            "gems":[9,27],
            "phantomhorizontal":[29],
            "phantomhorizontalLeft":[7]
         },{
            "row":42,
            "phantomvertical":[14,22]
         },{
            "row":44,
            "gems":[9,27]
         },{
            "row":45,
            "gems":[18]
         },{
            "row":48,
            "gems":[11,25]
         },{
            "row":49,
            "gems":[7,29]
         },{
            "row":51,
            "gems":[5,14,22,31]
         },{
            "row":53,
            "gems":[11,25]
         },{
            "row":54,
            "gems":[7,29],
            "phantomidle":[18]
         },{
            "row":57,
            "phantomhorizontal":[6],
            "phantomhorizontalLeft":[30]
         },{
            "row":58,
            "gems":[1,35]
         },{
            "row":61,
            "gems":[13,23],
            "phantomidle":[8,28]
         },{
            "row":63,
            "gems":[3,15,21,33]
         },{
            "row":65,
            "gems":[13,23]
         },{
            "row":67,
            "gems":[3,9,27,33]
         },{
            "row":69,
            "gems":[15,21],
            "phantomhorizontal":[25],
            "phantomhorizontalLeft":[11]
         },{
            "row":71,
            "gems":[3,9,27,33]
         },{
            "row":73,
            "gems":[13,23]
         },{
            "row":75,
            "gems":[3,33]
         },{
            "row":76,
            "gems":[15,21],
            "phantomidle":[7,29]
         },{
            "row":79,
            "gems":[13,23]
         },{
            "row":80,
            "gems":[1,35]
         },{
            "row":82,
            "phantomidle":[13,23]
         },{
            "row":83,
            "gems":[3,33]
         },{
            "row":85,
            "phantomidle":[9,27]
         },{
            "row":88,
            "gems":[18]
         },{
            "row":91,
            "phantomhorizontal":[1,10],
            "phantomhorizontalLeft":[26,35]
         },{
            "row":94,
            "gems":[3,13,23,33]
         },{
            "row":97,
            "phantomhorizontal":[19,28],
            "phantomhorizontalLeft":[8,17]
         },{
            "row":100,
            "gems":[6,12,24,30],
            "phantomidle":[18]
         },{
            "row":102,
            "gems":[9,27]
         },{
            "row":105,
            "phantomhorizontal":[1,10],
            "phantomhorizontalLeft":[26,35]
         },{
            "row":109,
            "phantomidle":[13,23]
         },{
            "row":110,
            "gems":[7,29],
            "phantomverticalDown":[18]
         },{
            "row":114,
            "gems":[5,9,27,31]
         },{
            "row":116,
            "gems":[15,21]
         },{
            "row":118,
            "gems":[3,11,25,33]
         },{
            "row":120,
            "phantomvertical":[18]
         },{
            "row":122,
            "phantomvertical":[12,24]
         },{
            "row":124,
            "gems":[5,31]
         },{
            "row":126,
            "phantomhorizontal":[27],
            "phantomhorizontalLeft":[9]
         },{
            "row":128,
            "gems":[5,31]
         },{
            "row":130,
            "phantomidle":[18]
         },{
            "row":134,
            "gems":[5,11,25,31]
         },{
            "row":136,
            "gems":[7,29],
            "phantomidle":[18]
         },{
            "row":138,
            "gems":[15,21]
         },{
            "row":139,
            "phantomhorizontal":[27],
            "phantomhorizontalLeft":[9]
         },{
            "row":140,
            "gems":[3,33]
         },{
            "row":142,
            "gems":[5,31],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":145,
            "gems":[11,25],
            "phantomhorizontal":[1],
            "phantomhorizontalLeft":[35]
         },{
            "row":147,
            "gems":[11,25]
         },{
            "row":150,
            "phantomidle":[13,23]
         },{
            "row":151,
            "gems":[7,29]
         },{
            "row":152,
            "phantomvertical":[18]
         },{
            "row":153,
            "gems":[5,31]
         },{
            "row":157,
            "gems":[9,27],
            "phantomidle":[4,32]
         },{
            "row":160,
            "phantomverticalDown":[18]
         },{
            "row":161,
            "gems":[5,31]
         },{
            "row":164,
            "phantomidle":[11,25]
         },{
            "row":166,
            "gems":[3,33]
         },{
            "row":169,
            "phantomverticalDown":[5,31]
         },{
            "row":170,
            "gems":[11,25]
         },{
            "row":174,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":178,
            "gems":[11,25]
         },{
            "row":182,
            "gems":[7,29],
            "phantomhorizontal":[19],
            "phantomhorizontalLeft":[17]
         },{
            "row":188,
            "gems":[9,27]
         },{
            "row":189,
            "phantomidle":[18]
         },{
            "row":190,
            "phantomidle":[5,31]
         },{
            "row":193,
            "gems":[11,25]
         },{"ground":200}],[{
            "row":15,
            "gems":[3,33]
         },{
            "row":17,
            "gems":[7,29]
         },{
            "row":18,
            "phantomverticalDown":[18]
         },{
            "row":21,
            "gems":[7,15,21,29]
         },{
            "row":24,
            "gems":[9,13,23,27]
         },{
            "row":25,
            "phantomidle":[4,32]
         },{
            "row":27,
            "gems":[11,25]
         },{
            "row":29,
            "gems":[5,31]
         },{
            "row":31,
            "gems":[3,13,23,33]
         },{
            "row":33,
            "gems":[11,25],
            "phantomvertical":[18]
         },{
            "row":35,
            "gems":[5,31]
         },{
            "row":37,
            "phantomidle":[18]
         },{
            "row":38,
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":39,
            "gems":[9,27]
         },{
            "row":42,
            "gems":[5,13,23,31]
         },{
            "row":43,
            "phantomverticalDown":[18]
         },{
            "row":45,
            "phantomidle":[9,27]
         },{
            "row":48,
            "gems":[5,13,23,31]
         },{
            "row":51,
            "gems":[9,27]
         },{
            "row":54,
            "phantomidle":[5,31]
         },{
            "row":55,
            "phantomidle":[18]
         },{
            "row":58,
            "gems":[8,28]
         },{
            "row":60,
            "gems":[3,33],
            "phantomverticalDown":[18]
         },{
            "row":64,
            "gems":[3,12,24,33]
         },{
            "row":68,
            "gems":[5,31]
         },{
            "row":69,
            "gems":[15,21]
         },{
            "row":73,
            "gems":[11,25],
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":76,
            "gems":[15,21]
         },{
            "row":78,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":80,
            "gems":[4,32]
         },{
            "row":82,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":84,
            "gems":[15,21]
         },{
            "row":87,
            "gems":[11,25],
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":90,
            "gems":[1,35]
         },{
            "row":92,
            "gems":[3,33]
         },{
            "row":93,
            "phantomvertical":[18]
         },{
            "row":95,
            "gems":[9,27]
         },{
            "row":97,
            "gems":[7,29]
         },{
            "row":100,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":102,
            "phantomidle":[18]
         },{
            "row":103,
            "gems":[10,26]
         },{
            "row":106,
            "phantomidle":[14,22],
            "phantomhorizontal":[3],
            "phantomhorizontalLeft":[33]
         },{
            "row":109,
            "gems":[10,26]
         },{
            "row":110,
            "phantomidle":[18]
         },{
            "row":112,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":115,
            "gems":[10,26],
            "phantomidle":[18]
         },{
            "row":118,
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":121,
            "gems":[10,26]
         },{
            "row":123,
            "phantomidle":[5,31]
         },{
            "row":125,
            "gems":[11,25]
         },{
            "row":127,
            "phantomvertical":[18]
         },{
            "row":129,
            "gems":[3,15,21,33]
         },{
            "row":132,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":133,
            "gems":[7,29]
         },{
            "row":135,
            "gems":[15,21]
         },{
            "row":137,
            "phantomidle":[18],
            "phantomhorizontal":[5],
            "phantomhorizontalLeft":[31]
         },{
            "row":139,
            "gems":[7,29]
         },{
            "row":140,
            "phantomverticalDown":[18]
         },{
            "row":141,
            "gems":[13,23]
         },{
            "row":143,
            "gems":[5,31]
         },{
            "row":147,
            "gems":[3,11,25,33]
         },{
            "row":150,
            "phantomhorizontal":[7],
            "phantomhorizontalLeft":[29]
         },{
            "row":151,
            "gems":[1,35]
         },{
            "row":153,
            "gems":[9,27]
         },{
            "row":156,
            "phantomhorizontal":[27],
            "phantomhorizontalLeft":[9]
         },{
            "row":157,
            "gems":[13,23]
         },{
            "row":160,
            "gems":[11,25],
            "phantomidle":[18]
         },{
            "row":163,
            "gems":[9,27]
         },{
            "row":165,
            "gems":[18]
         },{
            "row":166,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":169,
            "gems":[9,27]
         },{
            "row":171,
            "gems":[15,21]
         },{
            "row":175,
            "gems":[13,23],
            "phantomidle":[18]
         },{
            "row":176,
            "gems":[7,29]
         },{
            "row":179,
            "gems":[5,31]
         },{
            "row":182,
            "phantomhorizontal":[23],
            "phantomhorizontalLeft":[13]
         },{
            "row":184,
            "gems":[9,27]
         },{
            "row":187,
            "phantomvertical":[18]
         },{
            "row":188,
            "gems":[7,29]
         },{
            "row":190,
            "gems":[3,33]
         },{
            "row":191,
            "phantomhorizontal":[21],
            "phantomhorizontalLeft":[15]
         },{
            "row":193,
            "gems":[5,31]
         },{"ground":200}]];
      }
   }
}

