package game
{
   import flash.utils.Dictionary;
   import game.artPrintPlayPortrait.ArtPrintPlayPortrait;
   import game.artStudioGridDrawing.ArtStudioGridDrawing;
   import game.artStudioPainting.ArtStudioPainting;
   import game.artStudioPottery.ArtStudioPottery;
   import game.artStudioPrint.ArtStudioPrint;
   import game.bradyChemistrySet.BradyChemistrySet;
   import game.bradyExpeditions.BradyExpeditions;
   import game.candyCatcher.CandyCatcher;
   import game.cottonCandy.CottonCandy;
   import game.distanceChallenge.DistanceChallenge;
   import game.dolphinRace.DolphinRace;
   import game.dunkAPhantom.DunkAPhantom;
   import game.eagleFlap.EagleFlap;
   import game.fallingPhantoms.FallingPhantoms;
   import game.fashionShow.FashionShow;
   import game.fastFoodies.FastFoodies;
   import game.feedingFrenzy.FeedingFrenzy;
   import game.fortSmasher.FortSmasher;
   import game.gemBreaker.GemBreaker;
   import game.hedgeHog.HedgeHog;
   import game.horseRace.HorseRace;
   import game.microBambooHarvest.MicroBambooHarvest;
   import game.microCrane.MicroCrane;
   import game.microDucky.MicroDucky;
   import game.microGameInvasion.MicroGameInvasion;
   import game.microGoldPanning.MicroGoldPanning;
   import game.microHotCocoa.MicroHotCocoa;
   import game.microMiraSays.MicroMiraSays;
   import game.microOatHarvest.MicroOatHarvest;
   import game.microPetSalon.MicroPetSalon;
   import game.microPetWash.MicroPetWash;
   import game.microPhantom.MicroPhantom;
   import game.microPopcorn.MicroPopcorn;
   import game.microPuppy.MicroPuppy;
   import game.microSmoothie.MicroSmoothie;
   import game.microSnake.MicroSnake;
   import game.microStoneMining.MicroStoneMining;
   import game.microWoodGather.MicroWoodGather;
   import game.miniGame_Memory.MiniGame_Memory;
   import game.moatMadness.MoatMadness;
   import game.pVP_Bowling.PVP_Bowling;
   import game.pVP_ConnectFour.PVP_ConnectFour;
   import game.pVP_Marbles.PVP_Marbles;
   import game.pVP_Memory.PVP_Memory;
   import game.pVP_RockPaperScissor.PVP_RockPaperScissor;
   import game.pVP_Scooped.PVP_Scooped;
   import game.pVP_ShellGame.PVP_ShellGame;
   import game.pVP_TicTacToe.PVP_TicTacToe;
   import game.pachinko.Pachinko;
   import game.parachuteGlider.ParachuteGlider;
   import game.phantomFighter.PhantomFighter;
   import game.phantomsTreasure.PhantomsTreasure;
   import game.pillBugs.PillBugs;
   import game.questParachuteGlider.QuestParachuteGlider;
   import game.riverRace.RiverRace;
   import game.safetyQuiz.SafetyQuiz;
   import game.shootingGallery.ShootingGallery;
   import game.skeeball.Skeeball;
   import game.spiderShooter.SpiderShooter;
   import game.spotOn.SpotOn;
   import game.superSort.SuperSort;
   import game.touchPool.TouchPool;
   import game.towerDefense.TowerDefense;
   import game.trivia.Trivia;
   import game.trueFalse.TrueFalse;
   import game.twister.Twister;
   import game.whackPhantom.WhackPhantom;
   import game.windRider.WindRider;
   
   public class IncludeMinigames
   {
      public static const minigameFullyQualifiedNames:Dictionary = new Dictionary();
      
      public function IncludeMinigames()
      {
         super();
      }
      
      public static function init() : void
      {
         ArtPrintPlayPortrait;
         minigameFullyQualifiedNames["ArtPrintPlayPortrait"] = "game.artPrintPlayPortrait.ArtPrintPlayPortrait";
         ArtStudioGridDrawing;
         minigameFullyQualifiedNames["ArtStudioGridDrawing"] = "game.artStudioGridDrawing.ArtStudioGridDrawing";
         ArtStudioPainting;
         minigameFullyQualifiedNames["ArtStudioPainting"] = "game.artStudioPainting.ArtStudioPainting";
         ArtStudioPottery;
         minigameFullyQualifiedNames["ArtStudioPottery"] = "game.artStudioPottery.ArtStudioPottery";
         ArtStudioPrint;
         minigameFullyQualifiedNames["ArtStudioPrint"] = "game.artStudioPrint.ArtStudioPrint";
         BradyChemistrySet;
         minigameFullyQualifiedNames["BradyChemistrySet"] = "game.bradyChemistrySet.BradyChemistrySet";
         BradyExpeditions;
         minigameFullyQualifiedNames["BradyExpeditions"] = "game.bradyExpeditions.BradyExpeditions";
         CandyCatcher;
         minigameFullyQualifiedNames["CandyCatcher"] = "game.candyCatcher.CandyCatcher";
         CottonCandy;
         minigameFullyQualifiedNames["CottonCandy"] = "game.cottonCandy.CottonCandy";
         DistanceChallenge;
         minigameFullyQualifiedNames["DistanceChallenge"] = "game.distanceChallenge.DistanceChallenge";
         DolphinRace;
         minigameFullyQualifiedNames["DolphinRace"] = "game.dolphinRace.DolphinRace";
         DunkAPhantom;
         minigameFullyQualifiedNames["DunkAPhantom"] = "game.dunkAPhantom.DunkAPhantom";
         EagleFlap;
         minigameFullyQualifiedNames["EagleFlap"] = "game.eagleFlap.EagleFlap";
         FallingPhantoms;
         minigameFullyQualifiedNames["FallingPhantoms"] = "game.fallingPhantoms.FallingPhantoms";
         FashionShow;
         minigameFullyQualifiedNames["FashionShow"] = "game.fashionShow.FashionShow";
         FastFoodies;
         minigameFullyQualifiedNames["FastFoodies"] = "game.fastFoodies.FastFoodies";
         FeedingFrenzy;
         minigameFullyQualifiedNames["FeedingFrenzy"] = "game.feedingFrenzy.FeedingFrenzy";
         FortSmasher;
         minigameFullyQualifiedNames["FortSmasher"] = "game.fortSmasher.FortSmasher";
         GemBreaker;
         minigameFullyQualifiedNames["GemBreaker"] = "game.gemBreaker.GemBreaker";
         HedgeHog;
         minigameFullyQualifiedNames["HedgeHog"] = "game.hedgeHog.HedgeHog";
         HorseRace;
         minigameFullyQualifiedNames["HorseRace"] = "game.horseRace.HorseRace";
         MicroBambooHarvest;
         minigameFullyQualifiedNames["MicroBambooHarvest"] = "game.microBambooHarvest.MicroBambooHarvest";
         MicroCrane;
         minigameFullyQualifiedNames["MicroCrane"] = "game.microCrane.MicroCrane";
         MicroDucky;
         minigameFullyQualifiedNames["MicroDucky"] = "game.microDucky.MicroDucky";
         MicroGameInvasion;
         minigameFullyQualifiedNames["MicroGameInvasion"] = "game.microGameInvasion.MicroGameInvasion";
         MicroGoldPanning;
         minigameFullyQualifiedNames["MicroGoldPanning"] = "game.microGoldPanning.MicroGoldPanning";
         MicroHotCocoa;
         minigameFullyQualifiedNames["MicroHotCocoa"] = "game.microHotCocoa.MicroHotCocoa";
         MicroMiraSays;
         minigameFullyQualifiedNames["MicroMiraSays"] = "game.microMiraSays.MicroMiraSays";
         MicroOatHarvest;
         minigameFullyQualifiedNames["MicroOatHarvest"] = "game.microOatHarvest.MicroOatHarvest";
         MicroPetSalon;
         minigameFullyQualifiedNames["MicroPetSalon"] = "game.microPetSalon.MicroPetSalon";
         MicroPetWash;
         minigameFullyQualifiedNames["MicroPetWash"] = "game.microPetWash.MicroPetWash";
         MicroPhantom;
         minigameFullyQualifiedNames["MicroPhantom"] = "game.microPhantom.MicroPhantom";
         MicroPopcorn;
         minigameFullyQualifiedNames["MicroPopcorn"] = "game.microPopcorn.MicroPopcorn";
         MicroPuppy;
         minigameFullyQualifiedNames["MicroPuppy"] = "game.microPuppy.MicroPuppy";
         MicroSmoothie;
         minigameFullyQualifiedNames["MicroSmoothie"] = "game.microSmoothie.MicroSmoothie";
         MicroSnake;
         minigameFullyQualifiedNames["MicroSnake"] = "game.microSnake.MicroSnake";
         MicroStoneMining;
         minigameFullyQualifiedNames["MicroStoneMining"] = "game.microStoneMining.MicroStoneMining";
         MicroWoodGather;
         minigameFullyQualifiedNames["MicroWoodGather"] = "game.microWoodGather.MicroWoodGather";
         MiniGame_Memory;
         minigameFullyQualifiedNames["MiniGame_Memory"] = "game.miniGame_Memory.MiniGame_Memory";
         MoatMadness;
         minigameFullyQualifiedNames["MoatMadness"] = "game.moatMadness.MoatMadness";
         PVP_Bowling;
         minigameFullyQualifiedNames["PVP_Bowling"] = "game.pVP_Bowling.PVP_Bowling";
         PVP_ConnectFour;
         minigameFullyQualifiedNames["PVP_ConnectFour"] = "game.pVP_ConnectFour.PVP_ConnectFour";
         PVP_Marbles;
         minigameFullyQualifiedNames["PVP_Marbles"] = "game.pVP_Marbles.PVP_Marbles";
         PVP_Memory;
         minigameFullyQualifiedNames["PVP_Memory"] = "game.pVP_Memory.PVP_Memory";
         PVP_RockPaperScissor;
         minigameFullyQualifiedNames["PVP_RockPaperScissor"] = "game.pVP_RockPaperScissor.PVP_RockPaperScissor";
         PVP_Scooped;
         minigameFullyQualifiedNames["PVP_Scooped"] = "game.pVP_Scooped.PVP_Scooped";
         PVP_ShellGame;
         minigameFullyQualifiedNames["PVP_ShellGame"] = "game.pVP_ShellGame.PVP_ShellGame";
         PVP_TicTacToe;
         minigameFullyQualifiedNames["PVP_TicTacToe"] = "game.pVP_TicTacToe.PVP_TicTacToe";
         Pachinko;
         minigameFullyQualifiedNames["Pachinko"] = "game.pachinko.Pachinko";
         ParachuteGlider;
         minigameFullyQualifiedNames["ParachuteGlider"] = "game.parachuteGlider.ParachuteGlider";
         PhantomFighter;
         minigameFullyQualifiedNames["PhantomFighter"] = "game.phantomFighter.PhantomFighter";
         PhantomsTreasure;
         minigameFullyQualifiedNames["PhantomsTreasure"] = "game.phantomsTreasure.PhantomsTreasure";
         PillBugs;
         minigameFullyQualifiedNames["PillBugs"] = "game.pillBugs.PillBugs";
         QuestParachuteGlider;
         minigameFullyQualifiedNames["QuestParachuteGlider"] = "game.questParachuteGlider.QuestParachuteGlider";
         RiverRace;
         minigameFullyQualifiedNames["RiverRace"] = "game.riverRace.RiverRace";
         SafetyQuiz;
         minigameFullyQualifiedNames["SafetyQuiz"] = "game.safetyQuiz.SafetyQuiz";
         ShootingGallery;
         minigameFullyQualifiedNames["ShootingGallery"] = "game.shootingGallery.ShootingGallery";
         Skeeball;
         minigameFullyQualifiedNames["Skeeball"] = "game.skeeball.Skeeball";
         SpiderShooter;
         minigameFullyQualifiedNames["SpiderShooter"] = "game.spiderShooter.SpiderShooter";
         SpotOn;
         minigameFullyQualifiedNames["SpotOn"] = "game.spotOn.SpotOn";
         SuperSort;
         minigameFullyQualifiedNames["SuperSort"] = "game.superSort.SuperSort";
         TouchPool;
         minigameFullyQualifiedNames["TouchPool"] = "game.touchPool.TouchPool";
         TowerDefense;
         minigameFullyQualifiedNames["TowerDefense"] = "game.towerDefense.TowerDefense";
         Trivia;
         minigameFullyQualifiedNames["Trivia"] = "game.trivia.Trivia";
         TrueFalse;
         minigameFullyQualifiedNames["TrueFalse"] = "game.trueFalse.TrueFalse";
         Twister;
         minigameFullyQualifiedNames["Twister"] = "game.twister.Twister";
         WhackPhantom;
         minigameFullyQualifiedNames["WhackPhantom"] = "game.whackPhantom.WhackPhantom";
         WindRider;
         minigameFullyQualifiedNames["WindRider"] = "game.windRider.WindRider";
      }
   }
}

