name: Build

on:
    push:
        branches:
            - master

jobs:
    build_electron:
        name: Build Electron App
        runs-on: macos-14

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Check commit message for version number
              run: |
                  if ! echo "${{ github.event.head_commit.message }}" | grep -E '[0-9]+\.[0-9]+\.[0-9]+'; then
                      echo "Commit message does not contain a version number. Skipping build."
                      exit 1
                  fi

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.11.0'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build Electron App
              run: npm run build:win && npm run build:mac
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Rename macOS files
              run: |
                  mv build/*.dmg build/Jam-latest.dmg
                  mv build/*.dmg.blockmap build/Jam-latest.dmg.blockmap
              working-directory: .

            - name: Rename Windows files
              run: |
                  mv build/*.exe build/Jam-Setup-latest.exe
                  mv build/*.exe.blockmap build/Jam-Setup-latest.exe.blockmap
              working-directory: .

            - name: Move metadata files
              run: |
                  mv build/latest-mac.yml build/latest.yml
              working-directory: .

            - name: Create and Publish GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: latest
                  name: Latest Build
                  draft: false
                  prerelease: false
                  files: |
                      build/Jam-latest.dmg
                      build/Jam-latest.dmg.blockmap
                      build/Jam-Setup-latest.exe
                      build/Jam-Setup-latest.exe.blockmap
                      build/latest.yml
                      build/latest-mac.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
