name: Build

on:
    push:
        branches:
            - master

jobs:
    build_electron:
        name: Build Electron App
        runs-on: macos-14

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Extract version number from commit message
              id: extract_version
              run: |
                  VERSION=$(echo "${{ github.event.head_commit.message }}" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
                  if [ -z "$VERSION" ]; then
                      echo "Commit message does not contain a version number. Skipping build."
                      exit 1
                  fi
                  echo "VERSION=$VERSION" >> $GITHUB_ENV

            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: '22.11.0'
                  cache: 'npm'

            - name: Install dependencies
              run: npm install

            - name: Build Windows App
              run: npm run build:win
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Build macOS App
              run: npm run build:mac
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Rename macOS files
              run: |
                  mv build/*.dmg build/Jam-${{ env.VERSION }}.dmg
                  mv build/*.dmg.blockmap build/Jam-${{ env.VERSION }}.dmg.blockmap
              working-directory: .

            - name: Rename Windows files
              run: |
                  mv build/*.exe build/Jam-Setup-${{ env.VERSION }}.exe
                  mv build/*.exe.blockmap build/Jam-Setup-${{ env.VERSION }}.exe.blockmap
              working-directory: .

            - name: Move metadata files
              run: |
                  mv build/latest-mac.yml build/latest.yml
              working-directory: .

            - name: Create and Publish GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: ${{ env.VERSION }}
                  name: Release ${{ env.VERSION }}
                  draft: false
                  prerelease: false
                  files: |
                      build/Jam-${{ env.VERSION }}.dmg
                      build/Jam-${{ env.VERSION }}.dmg.blockmap
                      build/Jam-Setup-${{ env.VERSION }}.exe
                      build/Jam-Setup-${{ env.VERSION }}.exe.blockmap
                      build/latest.yml
                      build/latest-mac.yml
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}